"""add priority and due date to tasks

Revision ID: 230a3744fabd
Revises: 7db8d95cb1ec
Create Date: 2026-09-10 10:36:01.297959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230a3744fabd'
down_revision: Union[str, Sequence[str], None] = '7db8d95cb1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('user_tasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.alter_column('user_tasks', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.execute("DELETE FROM user_tasks WHERE user_id IS NULL")
    op.alter_column('user_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_user_tasks_id'), 'user_tasks', ['id'], unique=False)
    op.drop_constraint(op.f('user_tasks_user_id_fkey'), 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_user_id_fkey'), 'user_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_tasks_id'), table_name='user_tasks')
    op.alter_column('user_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_tasks', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user_tasks', 'due_date')
    op.drop_column('user_tasks', 'priority')
    # ### end Alembic commands ###
